import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/src/components/ui/toaster";
import { cn } from "../lib/utils";
import Provider from "../components/Provider";
import Notification from "../components/Notification";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-[#ffff] font-sans antialiased",
          inter.variable
        )}
      >
        <Provider>
          <div>
            {children}
            <Toaster />
            <Notification />
          </div>
        </Provider>
      </body>
    </html>
  );
}
